# Generated by Django 4.1.1 on 2022-10-01 07:29

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('email', models.EmailField(max_length=80, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('active', models.PositiveSmallIntegerField(default=0, verbose_name='active')),
                ('role', models.CharField(default='NORMAL', max_length=10, verbose_name='role')),
                ('login_attempts', models.PositiveSmallIntegerField(db_column='loginAttempts', default=0, verbose_name='loginAttempts')),
                ('register_date', models.DateTimeField(auto_now_add=True, db_column='registerDate', verbose_name='registerDate')),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('email', 'username', 'uuid')},
            },
        ),
    ]
