# Generated by Django 4.1.2 on 2022-10-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
