# Generated by Django 4.1.2 on 2022-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(db_column='lastLogin', default=None, null=True, verbose_name='lastLogin'),
        ),
    ]
