# Generated by Django 4.1.2 on 2022-10-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_active'),
        ('users', '0004_alter_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(db_column='company', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
