# Generated by Django 4.1.1 on 2022-09-30 05:31

import api.mixins.validate_model
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('cif', models.CharField(max_length=9, unique=True, verbose_name='cif')),
                ('email', models.EmailField(max_length=80, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=24, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=24, null=True, verbose_name='country')),
                ('postal_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='postal_code')),
                ('sector', models.CharField(blank=True, max_length=80, null=True, verbose_name='sector')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'db_table': 'company',
                'unique_together': {('uuid', 'email', 'name', 'cif')},
            },
            bases=(api.mixins.validate_model.ValidateModelMixin, models.Model),
        ),
    ]
