# Generated by Django 4.1.2 on 2022-10-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='active',
        ),
    ]
