# Generated by Django 4.1.2 on 2022-10-19 20:23

import api.mixins.validate_model
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('path', models.CharField(max_length=30, verbose_name='path')),
                ('dataset', models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'db_table': 'image',
                'unique_together': {('dataset', 'name')},
            },
            bases=(api.mixins.validate_model.ValidateModelMixin, models.Model),
        ),
    ]
