# Generated by Django 4.1.2 on 2022-10-19 20:55

import api.mixins.validate_model
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabels',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('image', models.ForeignKey(db_column='image', on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('label', models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.CASCADE, to='api.label')),
            ],
            options={
                'db_table': 'image_labels',
            },
            bases=(api.mixins.validate_model.ValidateModelMixin, models.Model),
        ),
    ]
