# Generated by Django 4.1.2 on 2022-10-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_storage_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
