# Generated by Django 4.1.2 on 2022-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='storage_in',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='storage_in'),
        ),
    ]
