# Generated by Django 4.1.3 on 2022-11-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_company_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mark_to_train_at',
            field=models.DateTimeField(blank=True, db_column='markToTrainAt', null=True, verbose_name='markToTrainAt'),
        ),
        migrations.AddField(
            model_name='imagelabels',
            name='mark_to_train_at',
            field=models.DateTimeField(blank=True, db_column='markToTrainAt', null=True, verbose_name='markToTrainAt'),
        ),
    ]
