# Generated by Django 4.1.3 on 2022-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='storage_in',
            field=models.CharField(db_column='storageIn', max_length=240, verbose_name='storageIn'),
        ),
    ]
